language: python

python: '3.8'

os: linux

dist: xenial

cache: pip

install:
  - pip3 install -r requirements.txt

stages:
  - test
  - lint

jobs:
  include:
    - stage: test
      script:
        - bash config/run-tests.sh
    - stage: lint
      script:
        - pylint ./**/*.py
        # - pylint ./**/*.py | grep -w "Your code has been rated at (*/*)" | if >= 6

notifications:
  email:
    on_success: always
    on_failure: always
