language: python

python: '3.8'

os: linux

dist: xenial

cache: pip

install:
  - pip3 install -r requirements.txt

stages:
  - plagiarism_check
  - pr_name_check
  - test
  - lint

env:
  global:
    - PR_TITLE=$(curl https://github.com/${TRAVIS_REPO_SLUG}/pull/${TRAVIS_PULL_REQUEST} | grep "title" | head -1)

jobs:
  include:
    - stage: plagiarism_check
      script:
        - bash config/run_plagiarism_check.sh
    - stage: pr_name_check
      script:
        - python3 config/check_pr_title.py --pr-name $(echo ${PR_TITLE// /_})
    - stage: test
      script:
        - bash config/run-tests.sh
    - stage: lint
      script:
        - bash config/run-lint.sh

notifications:
  email:
    on_success: always
    on_failure: always
