language: python

python: '3.8'

os: linux

dist: xenial

cache: pip

before_install:
  - git lfs pull

install:
  - pip3 install -r requirements.txt

stages:
  - test
  - lint
  - start_py

jobs:
  include:
    - stage: test
      script:
        - bash config/run-tests.sh
    - stage: lint
      script:
        - bash config/run-lint.sh
    - stage: start_py
      script:
        - bash config/run-start.sh

notifications:
  email:
    on_success: always
    on_failure: always
